version: 2

jobs:
  build:
    working_directory: ~/jsc-android-buildscripts
    machine: true
    environment:
      NDK_VERSION: r18
      SDK_VERSION: sdk-tools-linux-3859397.zip
      ANDROID_HOME: /home/circleci/android-sdk
      ANDROID_NDK: /home/circleci/android-ndk
    steps:
      - checkout
      - run:
          name: install android sdk
          command: |
            curl --silent --show-error --location --fail --retry 3 --output /tmp/${SDK_VERSION} https://dl.google.com/android/repository/${SDK_VERSION} && \
              mkdir -p ${ANDROID_HOME} && \
              unzip -q /tmp/${SDK_VERSION} -d ${ANDROID_HOME} && \
              rm /tmp/${SDK_VERSION}
            export PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
            mkdir ~/.android && echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
            yes | sdkmanager --licenses && sdkmanager --update
            sdkmanager \
              "tools" \
              "platform-tools" \
              "emulator" \
              "extras;android;m2repository" \
              "extras;google;m2repository" \
              "extras;google;google_play_services"
            sdkmanager \
              "build-tools;25.0.3" \
              "build-tools;27.0.3"
            sdkmanager "platforms;android-27"
      - run:
          name: install android ndk
          command: |
            export PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
            mkdir /tmp/android-ndk-tmp && \
              cd /tmp/android-ndk-tmp && \
              wget -q https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip &&
              unzip -q android-ndk-${NDK_VERSION}-linux-x86_64.zip && \
              mv ./android-ndk-${NDK_VERSION} ${ANDROID_NDK} && \
              cd ${ANDROID_NDK} && \
              rm -rf /tmp/android-ndk-tmp
            sdkmanager \
              "lldb;3.0" \
              "cmake;3.6.4111459"
      - run:
          name: install subversion
          command: |
            sudo apt-get update
            sudo apt-get install coreutils realpath curl git subversion python-dev ruby gperf -y
      # - run: npm run clean
      # - run: npm run download
      # - run: npm run start
      # - store_artifacts:
      #     path: dist/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
